sudo: required

services:
  - docker

before_install:
- docker pull centos:latest

script:
- docker build -t rpmbuild .
- docker ps -a
#- docker run -t rpmbuild -v /data . 

notifications:
  email: false
