sudo: required

services:
  - docker

script:
#- docker run -v /home/travis/build/robertdebock/rpmbuildtest:/data robertdebock/docker-centos-rpmbuild rpmbuild --define '_topdir /data' -ba /data/test.spec
- docker run -v /home/travis/build/robertdebock/rpmbuildtest:/data robertdebock/docker-centos-rpmbuild ls -l /data/test.spec

notifications:
  email: false
