sudo: required

services:
  - docker

script:
- docker run -v /home/travis/build/robertdebock/rpmbuildtest:/data robertdebock/docker-centos-rpmbuild /bin/sh -x /data/rpmbuild.sh -d /data -s test.spec

notifications:
  email: false
