sudo: required

services:
  - docker

before_install:
- docker pull centos:latest

script:
- docker run -v /home/travis/build/robertdebock/rpmbuildtest:/data centos:latest ls -la /data

notifications:
  email: false
