sudo: required

services:
  - docker

before_install:
- docker pull centos:latest

script:
#- docker build -t centos:rpmbuild .
- ls -la
- touch iets
- docker run -v ./:/data centos:latest ls -la /data
- ls -la

notifications:
  email: false
