sudo: required

services:
  - docker

script:
- docker run -v /home/travis/build/robertdebock/rpmbuildtest:/data robertdebock/docker-centos-rpmbuild /bin/sh /data/rpmbuild.sh

notifications:
  email: false
