sudo: required

services:
  - docker

script:
- docker run -v /home/travis/build/robertdebock/rpmbuildtest:/data robertdebock/docker-centos-rpmbuild rpmbuild -ba /data/test.spec

notifications:
  email: false
