sudo: required

services:
  - docker

before_install:
- docker pull centos:latest

script:
#- docker build -t centos:rpmbuild .
- docker run -v ./:/data centos:latest ls -l /data

notifications:
  email: false
