sudo: required

services:
  - docker

script:
- docker run -v $(pwd):/data robertdebock/docker-centos-rpmbuild /bin/sh /data/build.sh -d /data -s test.spec
- docker run -v $(pwd):/data robertdebock/docker-centos /bin/sh /data/test.sh

notifications:
  email: false
